AGooday.DncZero.Web/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AGooday.DncZero.Application.Interfaces;
using FluentValidation;
using AGooday.DncZero.Application.ViewModels;
using Microsoft.Extensions.Caching.Memory;
using AGooday.DncZero.Domain.Core.Notifications;
using MediatR;
using AGooday.DncZero.Domain.Models;

namespace AGooday.DncZero.Web.Controllers
{
    public class UsersController : BaseController
    {
        private readonly ILogger<UsersController> _logger;
        private readonly IUsersAppService _usersAppService;
        IValidator<UsersViewModel> _validator;
        private IMemoryCache _cache;
        // 将领域通知处理程序注入Controller
        private readonly DomainNotificationHandler _notifications;

        public UsersController(ILogger<UsersController> logger, IUsersAppService usersAppService, IMemoryCache cache, INotificationHandler<DomainNotification> notifications)
        {
            _logger = logger;
            _usersAppService = usersAppService;
            _cache = cache;
            // 强类型转换
            _notifications = (DomainNotificationHandler)notifications;
        }

        public async Task<IActionResult> Index()
        {
            //var users = _usersAppService.GetAll().OrderBy(o => o.Name);
            var users = await _usersAppService.ListAsync();
            return View(users);
        }

        // GET: Users/Details/5
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var usersViewModel = _usersAppService.GetById(id.Value);
            var usersViewModel = await _usersAppService.FindByIdAsync(id.Value);

            if (usersViewModel == null)
            {
                return NotFound();
            }

            return View(usersViewModel);
        }

        // GET: Users/Create
        // 页面
        //[Authorize(Policy = "CanWriteUsersData")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // 方法
        [HttpPost]
        //[ValidateAntiForgeryToken]
        //[Authorize(Policy = "CanWriteUsersData")]
        public ActionResult Create(UsersViewModel usersViewModel)
        {
            try
            {
                //_cache.Remove("ErrorData");
                //ViewBag.ErrorData = null;
                // 视图模型验证
                if (!ModelState.IsValid)
                    return View(usersViewModel);

                #region 删除命令验证
                ////添加命令验证
                //RegisterusersCommand registerusersCommand = new RegisterusersCommand(usersViewModel.Name, usersViewModel.Email, usersViewModel.BirthDate, usersViewModel.Phone);

                ////如果命令无效，证明有错误
                //if (!registerusersCommand.IsValid())
                //{
                //    List<string> errorInfo = new List<string>();
                //    //获取到错误，请思考这个Result从哪里来的 
                //    foreach (var error in registerusersCommand.ValidationResult.Errors)
                //    {
                //        errorInfo.Add(error.ErrorMessage);
                //    }
                //    //对错误进行记录，还需要抛给前台
                //    ViewBag.ErrorData = errorInfo;
                //    return View(usersViewModel);
                //} 
                #endregion

                // 执行添加方法
                _usersAppService.Create(usersViewModel);

                //var errorData = _cache.Get("ErrorData");
                //if (errorData == null)

                // 是否存在消息通知
                if (!_notifications.HasNotifications())
                    ViewBag.Sucesso = "Users Registered!";

                return View(usersViewModel);
            }
            catch (Exception e)
            {
                return View(e.Message);
            }
        }
        [HttpPost]
        public async Task<IActionResult> UpdateAsync([FromBody] UsersViewModel usersViewModel)
        {
            var response = await _usersAppService.ModifyAsync(usersViewModel); ;
            return ProduceResponse<Users>(response);
        }

        // GET: Users/Edit/5
        [HttpGet]
        //[Authorize(Policy = "CanWriteUsersData")]
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usersViewModel = _usersAppService.GetById(id.Value);

            if (usersViewModel == null)
            {
                return NotFound();
            }

            return View(usersViewModel);
        }

        // POST: Users/Edit/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        //[Authorize(Policy = "CanWriteUsersData")]
        public IActionResult Edit(UsersViewModel usersViewModel)
        {
            if (!ModelState.IsValid) return View(usersViewModel);

            _usersAppService.Update(usersViewModel);

            if (!_notifications.HasNotifications())
                ViewBag.Sucesso = "Users Updated!";

            return View(usersViewModel);
        }

        // GET: Users/Delete/5
        //[Authorize(Policy = "CanWriteOrRemoveUsersData")]
        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usersViewModel = _usersAppService.GetById(id.Value);

            if (usersViewModel == null)
            {
                return NotFound();
            }

            return View(usersViewModel);
        }

        // POST: Users/Delete/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        //[Authorize(Policy = "CanWriteOrRemoveUsersData")]
        public IActionResult DeleteConfirmed(Guid id)
        {
            _usersAppService.Remove(id);

            if (!_notifications.HasNotifications())
                return View(_usersAppService.GetById(id));

            ViewBag.Sucesso = "Users Removed!";
            return RedirectToAction("Index");
        }

        [Route("history/{id:guid}")]
        public JsonResult History(Guid id)
        {
            var usersHistoryData = _usersAppService.GetAllHistory(id);
            return Json(usersHistoryData);
        }
    }
}

AGooday.DncZero.Web/ViewComponents/AlertsViewComponent.cs
using AGooday.DncZero.Domain.Core.Notifications;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AGooday.DncZero.Web.ViewComponents
{
    public class AlertsViewComponent : ViewComponent
    {
        // 缓存注入，为了收录信息（错误方法，以后会用通知，通过领域事件来替换）
        // private IMemoryCache _cache;

        // 领域通知处理程序
        private readonly DomainNotificationHandler _notifications;

        // 构造函数注入
        public AlertsViewComponent(INotificationHandler<DomainNotification> notifications)
        {
            //_cache = cache;
            _notifications = (DomainNotificationHandler)notifications;
        }


        /// <summary>
        /// Alerts 视图组件
        /// 可以异步，也可以同步，注意方法名称，同步的时候是Invoke
        /// 我写异步是为了为以后做准备
        /// </summary>
        /// <returns></returns>
        public async Task<IViewComponentResult> InvokeAsync()
        {
            //// 获取到缓存中的错误信息
            //var errorData = _cache.Get("ErrorData");
            //var notificacoes = await Task.Run(() => (List<string>)errorData);
            //// 遍历添加到ViewData.ModelState 中
            //notificacoes?.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c));

            // 从通知处理程序中，获取全部通知信息，并返回给前台
            var notificacoes = await Task.FromResult((_notifications.GetNotifications()));
            notificacoes.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Value));

            return View();
        }
    }
}

AGooday.DncZero.Web/Views/Users/Create.cshtml
@model UsersViewModel
@{
    ViewData["Title"] = "Register New Users";
}
<h2>@ViewData["Title"]</h2>
<form asp-action="Create" method="post">
    <div class="form-horizontal">
        <hr />
        <!--<input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="Type" />
        <input type="hidden" asp-for="MtypeId" />
        @*<input type="hidden" asp-for="NickName" />
        <input type="hidden" asp-for="Surname" />
        <input type="hidden" asp-for="Name" />
        <input type="hidden" asp-for="RealName" />
        @*<input type="hidden" asp-for="Phone" />
        <input type="hidden" asp-for="Email" />
        <input type="hidden" asp-for="BirthDate" />
        <input type="hidden" asp-for="Sex" />*@
        <input type="hidden" asp-for="Age" />
        <input type="hidden" asp-for="Gravatar" />
        <input type="hidden" asp-for="Avatar" />
        <input type="hidden" asp-for="Motto" />
        <input type="hidden" asp-for="Bio" />
        <input type="hidden" asp-for="Idcard" />
        <input type="hidden" asp-for="Major" />
        <input type="hidden" asp-for="Polity" />
        <input type="hidden" asp-for="NowState" />
        <input type="hidden" asp-for="State" />
        @*<input type="hidden" asp-for="Province" />
        <input type="hidden" asp-for="City" />
        <input type="hidden" asp-for="County" />
        <input type="hidden" asp-for="Street" />
        <input type="hidden" asp-for="Detailed" />*@
        <input type="hidden" asp-for="Company" />
        <input type="hidden" asp-for="Website" />
        <input type="hidden" asp-for="Weibo" />
        <input type="hidden" asp-for="Blog" />
        <input type="hidden" asp-for="Url" />
        <input type="hidden" asp-for="RegisterTime" />
        <input type="hidden" asp-for="RegisterIp" />
        <input type="hidden" asp-for="LastLoginTime" />
        <input type="hidden" asp-for="LastLoginIp" />
        <input type="hidden" asp-for="LastModifiedTime" />
        <input type="hidden" asp-for="LastModifiedIp" />
        <input type="hidden" asp-for="Sort" />-->
        @* https://docs.microsoft.com/zh-cn/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-3.1 *@
        @* https://docs.microsoft.com/zh-cn/aspnet/core/mvc/views/view-components?view=aspnetcore-3.1 *@
        @* Replacing classic Validation Summary to Custom ViewComponent as TagHelper *@
        @* 翻译：将经典验证摘要替换为自定义视图组件作为标记助手 *@

        @* 方式一(可用，但不推荐) *@
        @*@await Component.InvokeAsync("Alerts")*@

        <!-- 方式二 如果使用这个方法，请记得在_ViewImports.cshtml 中，导入@addTagHelper "*, AGooday.DncZero.Web" -->
        <vc:alerts />

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="NickName" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <input asp-for="NickName" class="form-control" />
                    <span asp-validation-for="NickName" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="RealName" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <input asp-for="RealName" class="form-control" />
                    <span asp-validation-for="RealName" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Surname" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <input asp-for="Surname" class="form-control" />
                    <span asp-validation-for="Surname" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Name" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Phone" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Email" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <input asp-for="Email" class="form-control" placeholder="dnczero@dnc.com" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="BirthDate" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <input asp-for="BirthDate" class="form-control" />
                    <span asp-validation-for="BirthDate" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Sex" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <div class="custom-control custom-radio custom-control-inline">
                        <input asp-for="Sex" type="radio" id="female" name="Sex" class="custom-control-input" value="0">
                        <label class="custom-control-label" for="female">女性</label>
                    </div>
                    <div class="custom-control custom-radio custom-control-inline">
                        <input asp-for="Sex" type="radio" id="male" name="Sex" class="custom-control-input" value="1">
                        <label class="custom-control-label" for="male">男性</label>
                    </div>
                    <div class="custom-control custom-radio custom-control-inline">
                        <input asp-for="Sex" type="radio" id="other" name="Sex" class="custom-control-input" value="2">
                        <label class="custom-control-label" for="other">其他</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Province" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <input asp-for="Province" class="form-control" />
                    <span asp-validation-for="Province" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="City" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="County" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <input asp-for="County" class="form-control" />
                    <span asp-validation-for="County" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Street" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <input asp-for="Street" class="form-control" />
                    <span asp-validation-for="Street" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Detailed" class="col-md-6 control-label"></label>
            <div class="col-md-12">
                <input asp-for="Detailed" class="form-control" />
                <span asp-validation-for="Detailed" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-12">
                <input type="submit" value="Save" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-info">Back to List</a>
            </div>
        </div>
    </div>
</form>

AGooday.DncZero.Web/Views/Users/Details.cshtml
@model UsersViewModel
@{
    ViewData["Title"] = "Users Details";
}
<h2>@ViewData["Title"]</h2>
<div>
    <hr />
    <div class="row">
        <div class="col-md-3">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.NickName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.NickName)
                </dd>
            </dl>
        </div>
        <div class="col-md-3">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.RealName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.RealName)
                </dd>
            </dl>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Surname)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Surname)
                </dd>
            </dl>
        </div>
        <div class="col-md-3">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>
            </dl>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Phone)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Phone)
                </dd>
            </dl>
        </div>
        <div class="col-md-3">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Email)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Email)
                </dd>
            </dl>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.BirthDate)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.BirthDate)
                </dd>
            </dl>
        </div>
        <div class="col-md-3">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Sex)
                </dt>
                <dd>
                    <div class="custom-control custom-radio custom-control-inline">
                        <input asp-for="Sex" type="radio" id="female" name="Sex" class="custom-control-input" value="0" disabled>
                        <label class="custom-control-label" for="female">女性</label>
                    </div>
                    <div class="custom-control custom-radio custom-control-inline">
                        <input asp-for="Sex" type="radio" id="male" name="Sex" class="custom-control-input" value="1" disabled>
                        <label class="custom-control-label" for="male">男性</label>
                    </div>
                    <div class="custom-control custom-radio custom-control-inline">
                        <input asp-for="Sex" type="radio" id="other" name="Sex" class="custom-control-input" value="2" disabled>
                        <label class="custom-control-label" for="other">其他</label>
                    </div>
                </dd>
            </dl>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Province)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Province)
                </dd>
            </dl>
        </div>
        <div class="col-md-3">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.City)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.City)
                </dd>
            </dl>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.County)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.County)
                </dd>
            </dl>
        </div>
        <div class="col-md-3">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Street)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Street)
                </dd>
            </dl>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Detailed)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Detailed)
                </dd>
            </dl>
        </div>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit</a>
    <a asp-action="Index" class="btn btn-info">Back to List</a>
</div>

AGooday.DncZero.Web/Views/Users/Edit.cshtml
@model UsersViewModel
@{
    ViewData["Title"] = "Edit Users";
}
<h2>@ViewData["Title"]</h2>
<form asp-action="Edit" method="post">
    <div class="form-horizontal">
        <hr />
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="Type" />
        <input type="hidden" asp-for="MtypeId" />
        @*<input type="hidden" asp-for="NickName" />
            <input type="hidden" asp-for="Surname" />
            <input type="hidden" asp-for="Name" />
            <input type="hidden" asp-for="RealName" />
            @*<input type="hidden" asp-for="Phone" />
            <input type="hidden" asp-for="Email" />
            <input type="hidden" asp-for="BirthDate" />
            <input type="hidden" asp-for="Sex" />*@
        <input type="hidden" asp-for="Age" />
        <input type="hidden" asp-for="Gravatar" />
        <input type="hidden" asp-for="Avatar" />
        <input type="hidden" asp-for="Motto" />
        <input type="hidden" asp-for="Bio" />
        <input type="hidden" asp-for="Idcard" />
        <input type="hidden" asp-for="Major" />
        <input type="hidden" asp-for="Polity" />
        <input type="hidden" asp-for="NowState" />
        <input type="hidden" asp-for="State" />
        @*<input type="hidden" asp-for="Province" />
            <input type="hidden" asp-for="City" />
            <input type="hidden" asp-for="County" />
            <input type="hidden" asp-for="Street" />
            <input type="hidden" asp-for="Detailed" />*@
        <input type="hidden" asp-for="Company" />
        <input type="hidden" asp-for="Website" />
        <input type="hidden" asp-for="Weibo" />
        <input type="hidden" asp-for="Blog" />
        <input type="hidden" asp-for="Url" />
        <input type="hidden" asp-for="RegisterTime" />
        <input type="hidden" asp-for="RegisterIp" />
        <input type="hidden" asp-for="LastLoginTime" />
        <input type="hidden" asp-for="LastLoginIp" />
        <input type="hidden" asp-for="LastModifiedTime" />
        <input type="hidden" asp-for="LastModifiedIp" />
        <input type="hidden" asp-for="Sort" />

        @* Replacing classic Validation Summary to Custom ViewComponent as TagHelper *@
        @* 翻译：将经典验证摘要替换为自定义视图组件作为标记助手 *@

        @* 方式一(可用，但不推荐) *@
        @*@await Component.InvokeAsync("Alerts")*@

        <!-- 方式二 如果使用这个方法，请记得在_ViewImports.cshtml 中，导入@addTagHelper "*, AGooday.DncZero.Web" -->
        <vc:alerts />

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="NickName" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <input asp-for="NickName" class="form-control" />
                    <span asp-validation-for="NickName" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="RealName" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <input asp-for="RealName" class="form-control" />
                    <span asp-validation-for="RealName" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Surname" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <input asp-for="Surname" class="form-control" />
                    <span asp-validation-for="Surname" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Name" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Phone" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Email" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <input asp-for="Email" class="form-control" placeholder="dnczero@dnc.com" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="BirthDate" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <input asp-for="BirthDate" class="form-control" />
                    <span asp-validation-for="BirthDate" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Sex" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <div class="custom-control custom-radio custom-control-inline">
                        <input asp-for="Sex" type="radio" id="female" name="Sex" class="custom-control-input" value="0">
                        <label class="custom-control-label" for="female">女性</label>
                    </div>
                    <div class="custom-control custom-radio custom-control-inline">
                        <input asp-for="Sex" type="radio" id="male" name="Sex" class="custom-control-input" value="1">
                        <label class="custom-control-label" for="male">男性</label>
                    </div>
                    <div class="custom-control custom-radio custom-control-inline">
                        <input asp-for="Sex" type="radio" id="other" name="Sex" class="custom-control-input" value="2">
                        <label class="custom-control-label" for="other">其他</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Province" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <input asp-for="Province" class="form-control" />
                    <span asp-validation-for="Province" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="City" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="County" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <input asp-for="County" class="form-control" />
                    <span asp-validation-for="County" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Street" class="col-md-6 control-label"></label>
                <div class="col-md-12">
                    <input asp-for="Street" class="form-control" />
                    <span asp-validation-for="Street" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Detailed" class="col-md-6 control-label"></label>
            <div class="col-md-12">
                <input asp-for="Detailed" class="form-control" />
                <span asp-validation-for="Detailed" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-12">
                <input type="submit" value="Save" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-info">Back to List</a>
            </div>
        </div>
    </div>
</form>